<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Sharp.Shared\Sharp.Shared.csproj" />
    <ProjectReference Include="..\..\AdminManager\Shared\Sharp.Modules.AdminManager.Shared.csproj" />
    <ProjectReference Include="..\..\CommandManager\Shared\Sharp.Modules.CommandManager.Shared.csproj" />
    <ProjectReference Include="..\..\LocalizerManager\Shared\Sharp.Modules.LocalizerManager.Shared.csproj" />
  </ItemGroup>

</Project>
