<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>Sharp.Modules.AdminCommands</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Sharp.Shared\Sharp.Shared.csproj" Private="false" ExcludeAssets="runtime" />

		<ProjectReference Include="..\..\CommandManager\Shared\Sharp.Modules.CommandManager.Shared.csproj" Private="false"
		                  ExcludeAssets="runtime" />
		<ProjectReference Include="..\..\LocalizerManager\Shared\Sharp.Modules.LocalizerManager.Shared.csproj"
		                  Private="false" ExcludeAssets="runtime" />
		<ProjectReference Include="..\..\AdminManager\Shared\Sharp.Modules.AdminManager.Shared.csproj" Private="false"
		                  ExcludeAssets="runtime" />
		<ProjectReference Include="..\..\TargetingManager\Shared\Sharp.Modules.TargetingManager.Shared.csproj"
		                  Private="false" ExcludeAssets="runtime" />

		<ProjectReference Include="..\Shared\Sharp.Modules.AdminCommands.Shared.csproj" Private="false"
		                  ExcludeAssets="runtime" />
	</ItemGroup>
</Project>